In [1]:
import requests

In [39]:
url = f"https://comtrade.un.org/api/get/bulk/C/M/202012/643/HS?token=W0YHqyAzFmNGp02eQf4+BIQVkydVa8NYI8iWZKJj1BmDAX7wKz4yau8v1V4HYODsO2tiao8U4BLgNm9Dd41k6/yrXjv5U11MzfYRQs6aIXHvQWXFIwhucgVSp88vEkIk"
url = f"https://comtradeapi.un.org/bulk/v1/get/C/M/HS?reportercode=643&period=202001&key=W0YHqyAzFmNGp02eQf4+BIQVkydVa8NYI8iWZKJj1BmDAX7wKz4yau8v1V4HYODsO2tiao8U4BLgNm9Dd41k6"

# print(f"Retriving {filename} -- " + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
content = requests.get(url)

In [40]:
content.text

'{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }'

In [20]:
help(requests.get)

Help on function get in module requests.api:

get(url, params=None, **kwargs)
    Sends a GET request.

    :param url: URL for the new :class:`Request` object.
    :param params: (optional) Dictionary, list of tuples or bytes to send
        in the query string for the :class:`Request`.
    :param \*\*kwargs: Optional arguments that ``request`` takes.
    :return: :class:`Response <Response>` object
    :rtype: requests.Response

In [12]:
import json
import pandas as pd

In [13]:
working_directory = "./"

In [14]:
with open(working_directory + f"basic_info/years.json", "r") as fff:
    myjson = json.load(fff)
myjson = json.loads(myjson.replace("\r\n", "").replace("\ufeff",""))
myjson = myjson['results']
res = pd.DataFrame(myjson)
res.rename(columns={'text':'year'}, inplace = True)
res = res[['year']]
res = res[res['year']!='All']
res = res.astype({'year':int})

In [15]:
res

    year
1   2021
2   2020
3   2019
4   2018
5   2017
6   2016
7   2015
8   2014
9   2013
10  2012
11  2011
12  2010
13  2009
14  2008
15  2007
16  2006
17  2005
18  2004
19  2003
20  2002
21  2001
22  2000
23  1999
24  1998
25  1997
26  1996
27  1995
28  1994
29  1993
30  1992
31  1991
32  1990
33  1989
34  1988
35  1987
36  1986
37  1985
38  1984
39  1983
40  1982
41  1981
42  1980
43  1979
44  1978
45  1977
46  1976
47  1975
48  1974
49  1973
50  1972
51  1971
52  1970
53  1969
54  1968
55  1967
56  1966
57  1965
58  1964
59  1963
60  1962